POST http://localhost:8000/analyze
Content-Type: application/json

{
  "source_lang": "JA",
  "text": "私が好きなのは『龍が如く３』だよ。"
}

###

POST http://localhost:8000/chat
Accept: text/event-stream; charset=utf-8
Content-Type: application/json

{
  "messages": [],
  "text": "ユニティちゃんの好きなプレステ３のゲームを教えて！"
}