POST http://localhost:8000/analyze
Content-Type: application/json

{
  "source_lang": "JA",
  "text": "私はとても幸せ"
}

###

POST http://localhost:8000/chat
Content-Type: application/json

{
  "messages": [],
  "text": "こんにちは！"
}